title: EmoMix Emotion Mixing via Diffusion Models for Emotional Speech Synthesis
description: https://largeaudiomodel.com


theme: jekyll-theme-cayman

# github:
#   repository_url: https://github.com/EmoMixEmoMix/
